disabled = false
languageCode = "sl"
languageName = "SLovenian"
weight = 3
title = "Jousef šaj"

[params]
  displayName = "Slovenski"
  isoCode = "sl"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Uradna spletna stran Jousef šaj, navdušenca nad robotiko, inovatorja in razvijalca."
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   title = "Jousef šaj"
   email = "youremail@example.com"
   #image = "img/blowfish_logo.png"
   #imageQuality = 96
   headline = "Pozdravljeni! Sem Jousef. Večino svojega časa preživim s projekti robotike, igranjem glasbenih instrumentov, igranjem odbojke ali gledanjem televizije. Moji sanje so, da ustanovim podjetje za robotiko, ki bo pomagala in navdihovala druge. Občutite se svobodno, da me kontaktirate."
   bio = "Not much"
   links = [
      { email = "mailto:gamer.exe_shay@yahoo.com" },
      { github = "https://github.com/joseph-shay" },
      { instagram = "https://www.instagram.com/jjoseph_exe/" },
      { linkedin = "https://www.linkedin.com/in/joseph-shay-270448345?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app" },
      { x-twitter = "https://twitter.com/jjoseph_exe" },
      { youtube = "https://www.youtube.com/@Josephs.robotics" },

   ]
