disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Joseph Shay"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
    description = "Official website of Joseph Shay, a robotics enthusiast, innovator, and developer."
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Yousef Shaykholeslam"
   email = "youremail@example.com"
   #image = "img/blowfish_logo.png"
   #imageQuality = 96
   headline = "Hey! I am Yousef. I spend most of my time on robotic projects, playing intruments and play Volleyball, or watch movies. My dream is to start a robotics company that helps and inspires other. Feel free to reach out to me."
   bio = "Not much"
   links = [
      { email = "mailto:gamer.exe_shay@yahoo.com" },
      { github = "https://github.com/joseph-shay" },
      { instagram = "https://www.instagram.com/jjoseph_exe/" },
      { linkedin = "https://www.linkedin.com/in/joseph-shay-270448345?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app" },
      { x-twitter = "https://twitter.com/jjoseph_exe" },
      { youtube = "https://www.youtube.com/@Josephs.robotics" },

   ]
